# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/actions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import state_pb2 as proto_dot_state__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/actions.proto\x12\x07\x61\x63tions\x1a\x11proto/state.proto\"\x11\n\x0fGetStateRequest\"\\\n\x10GetStateResponse\x12\"\n\x06grants\x18\x01 \x03(\x0b\x32\x12.state.SignedGrant\x12$\n\x07records\x18\x02 \x03(\x0b\x32\x13.state.SignedRecordB.Z,github.com/smartin015/peerprint/pubsub/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.actions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,github.com/smartin015/peerprint/pubsub/proto'
  _GETSTATEREQUEST._serialized_start=51
  _GETSTATEREQUEST._serialized_end=68
  _GETSTATERESPONSE._serialized_start=70
  _GETSTATERESPONSE._serialized_end=162
# @@protoc_insertion_point(module_scope)
