# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstate.proto\x12\x05state\")\n\tSignature\x12\x0e\n\x06signer\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"R\n\x0cSignedRecord\x12\x1d\n\x06record\x18\x01 \x01(\x0b\x32\r.state.Record\x12#\n\tsignature\x18\x02 \x01(\x0b\x32\x10.state.Signature\"-\n\x04Rank\x12\x0b\n\x03num\x18\x01 \x01(\x04\x12\x0b\n\x03\x64\x65n\x18\x02 \x01(\x04\x12\x0b\n\x03gen\x18\x03 \x01(\x01\"t\n\x06Record\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x10\n\x08\x61pprover\x18\x02 \x01(\t\x12\x0c\n\x04tags\x18\x03 \x03(\t\x12\x19\n\x04rank\x18\x04 \x01(\x0b\x32\x0b.state.Rank\x12\x10\n\x08manifest\x18\x05 \x01(\t\x12\x0f\n\x07\x63reated\x18\x06 \x01(\x03\"^\n\x10SignedCompletion\x12%\n\ncompletion\x18\x01 \x01(\x0b\x32\x11.state.Completion\x12#\n\tsignature\x18\x02 \x01(\x0b\x32\x10.state.Signature\"\x8e\x01\n\nCompletion\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x11\n\tcompleter\x18\x02 \x01(\t\x12\x0e\n\x06\x63lient\x18\x03 \x01(\t\x12#\n\x04type\x18\x04 \x01(\x0e\x32\x15.state.CompletionType\x12\x17\n\x0f\x63ompleter_state\x18\x05 \x01(\x0c\x12\x11\n\ttimestamp\x18\x06 \x01(\x03*)\n\x0cLocationType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08IPFS_CID\x10\x01*V\n\x0e\x43ompletionType\x12\x1b\n\x17UNKNOWN_COMPLETION_TYPE\x10\x00\x12\r\n\tTOMBSTONE\x10\x01\x12\x0b\n\x07\x41\x43QUIRE\x10\x02\x12\x0b\n\x07RELEASE\x10\x03\x42.Z,github.com/smartin015/peerprint/pubsub/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,github.com/smartin015/peerprint/pubsub/proto'
  _LOCATIONTYPE._serialized_start=555
  _LOCATIONTYPE._serialized_end=596
  _COMPLETIONTYPE._serialized_start=598
  _COMPLETIONTYPE._serialized_end=684
  _SIGNATURE._serialized_start=22
  _SIGNATURE._serialized_end=63
  _SIGNEDRECORD._serialized_start=65
  _SIGNEDRECORD._serialized_end=147
  _RANK._serialized_start=149
  _RANK._serialized_end=194
  _RECORD._serialized_start=196
  _RECORD._serialized_end=312
  _SIGNEDCOMPLETION._serialized_start=314
  _SIGNEDCOMPLETION._serialized_end=408
  _COMPLETION._serialized_start=411
  _COMPLETION._serialized_end=553
# @@protoc_insertion_point(module_scope)
