# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import peerprint.server.pkg.proto.command_pb2 as command__pb2
import peerprint.server.pkg.proto.state_pb2 as state__pb2


class CommandStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/command.Command/Ping',
                request_serializer=command__pb2.HealthCheck.SerializeToString,
                response_deserializer=command__pb2.Ok.FromString,
                )
        self.GetId = channel.unary_unary(
                '/command.Command/GetId',
                request_serializer=command__pb2.GetIDRequest.SerializeToString,
                response_deserializer=command__pb2.GetIDResponse.FromString,
                )
        self.GetNetworks = channel.unary_unary(
                '/command.Command/GetNetworks',
                request_serializer=command__pb2.GetNetworksRequest.SerializeToString,
                response_deserializer=command__pb2.GetNetworksResponse.FromString,
                )
        self.Connect = channel.unary_unary(
                '/command.Command/Connect',
                request_serializer=command__pb2.ConnectRequest.SerializeToString,
                response_deserializer=command__pb2.Ok.FromString,
                )
        self.Disconnect = channel.unary_unary(
                '/command.Command/Disconnect',
                request_serializer=command__pb2.DisconnectRequest.SerializeToString,
                response_deserializer=command__pb2.Ok.FromString,
                )
        self.SetRecord = channel.unary_unary(
                '/command.Command/SetRecord',
                request_serializer=command__pb2.SetRecordRequest.SerializeToString,
                response_deserializer=command__pb2.Ok.FromString,
                )
        self.SetCompletion = channel.unary_unary(
                '/command.Command/SetCompletion',
                request_serializer=command__pb2.SetCompletionRequest.SerializeToString,
                response_deserializer=command__pb2.Ok.FromString,
                )
        self.Crawl = channel.unary_unary(
                '/command.Command/Crawl',
                request_serializer=command__pb2.CrawlRequest.SerializeToString,
                response_deserializer=command__pb2.CrawlResult.FromString,
                )
        self.StreamEvents = channel.unary_stream(
                '/command.Command/StreamEvents',
                request_serializer=command__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=command__pb2.Event.FromString,
                )
        self.StreamRecords = channel.unary_stream(
                '/command.Command/StreamRecords',
                request_serializer=command__pb2.StreamRecordsRequest.SerializeToString,
                response_deserializer=state__pb2.SignedRecord.FromString,
                )
        self.StreamCompletions = channel.unary_stream(
                '/command.Command/StreamCompletions',
                request_serializer=command__pb2.StreamCompletionsRequest.SerializeToString,
                response_deserializer=state__pb2.SignedCompletion.FromString,
                )


class CommandServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetworks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCompletion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Crawl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCompletions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommandServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=command__pb2.HealthCheck.FromString,
                    response_serializer=command__pb2.Ok.SerializeToString,
            ),
            'GetId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetId,
                    request_deserializer=command__pb2.GetIDRequest.FromString,
                    response_serializer=command__pb2.GetIDResponse.SerializeToString,
            ),
            'GetNetworks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetworks,
                    request_deserializer=command__pb2.GetNetworksRequest.FromString,
                    response_serializer=command__pb2.GetNetworksResponse.SerializeToString,
            ),
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=command__pb2.ConnectRequest.FromString,
                    response_serializer=command__pb2.Ok.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=command__pb2.DisconnectRequest.FromString,
                    response_serializer=command__pb2.Ok.SerializeToString,
            ),
            'SetRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRecord,
                    request_deserializer=command__pb2.SetRecordRequest.FromString,
                    response_serializer=command__pb2.Ok.SerializeToString,
            ),
            'SetCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCompletion,
                    request_deserializer=command__pb2.SetCompletionRequest.FromString,
                    response_serializer=command__pb2.Ok.SerializeToString,
            ),
            'Crawl': grpc.unary_unary_rpc_method_handler(
                    servicer.Crawl,
                    request_deserializer=command__pb2.CrawlRequest.FromString,
                    response_serializer=command__pb2.CrawlResult.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=command__pb2.StreamEventsRequest.FromString,
                    response_serializer=command__pb2.Event.SerializeToString,
            ),
            'StreamRecords': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRecords,
                    request_deserializer=command__pb2.StreamRecordsRequest.FromString,
                    response_serializer=state__pb2.SignedRecord.SerializeToString,
            ),
            'StreamCompletions': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCompletions,
                    request_deserializer=command__pb2.StreamCompletionsRequest.FromString,
                    response_serializer=state__pb2.SignedCompletion.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'command.Command', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Command(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/command.Command/Ping',
            command__pb2.HealthCheck.SerializeToString,
            command__pb2.Ok.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/command.Command/GetId',
            command__pb2.GetIDRequest.SerializeToString,
            command__pb2.GetIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNetworks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/command.Command/GetNetworks',
            command__pb2.GetNetworksRequest.SerializeToString,
            command__pb2.GetNetworksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/command.Command/Connect',
            command__pb2.ConnectRequest.SerializeToString,
            command__pb2.Ok.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/command.Command/Disconnect',
            command__pb2.DisconnectRequest.SerializeToString,
            command__pb2.Ok.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/command.Command/SetRecord',
            command__pb2.SetRecordRequest.SerializeToString,
            command__pb2.Ok.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/command.Command/SetCompletion',
            command__pb2.SetCompletionRequest.SerializeToString,
            command__pb2.Ok.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Crawl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/command.Command/Crawl',
            command__pb2.CrawlRequest.SerializeToString,
            command__pb2.CrawlResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/command.Command/StreamEvents',
            command__pb2.StreamEventsRequest.SerializeToString,
            command__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/command.Command/StreamRecords',
            command__pb2.StreamRecordsRequest.SerializeToString,
            state__pb2.SignedRecord.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamCompletions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/command.Command/StreamCompletions',
            command__pb2.StreamCompletionsRequest.SerializeToString,
            state__pb2.SignedCompletion.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
