# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/command.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/command.proto\x12\x07\x63ommand\"\r\n\x0bNotifyReady\"\x0c\n\nNotifySync\"\x0f\n\rNotifyMessage\"\r\n\x0bHealthCheck\"M\n\x0eNotifyProgress\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x1a\n\x12resolved_completer\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\"\x17\n\x05\x45rror\x12\x0e\n\x06reason\x18\x01 \x01(\t\"\x04\n\x02Ok\"\x07\n\x05GetID\"\x18\n\nIDResponse\x12\n\n\x02id\x18\x01 \x01(\t\"\'\n\x08SetTrust\x12\x0c\n\x04peer\x18\x01 \x01(\t\x12\r\n\x05trust\x18\x02 \x01(\x01\"3\n\x0eSetWorkability\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x13\n\x0bworkability\x18\x02 \x01(\x01\x42.Z,github.com/smartin015/peerprint/pubsub/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.command_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,github.com/smartin015/peerprint/pubsub/proto'
  _NOTIFYREADY._serialized_start=32
  _NOTIFYREADY._serialized_end=45
  _NOTIFYSYNC._serialized_start=47
  _NOTIFYSYNC._serialized_end=59
  _NOTIFYMESSAGE._serialized_start=61
  _NOTIFYMESSAGE._serialized_end=76
  _HEALTHCHECK._serialized_start=78
  _HEALTHCHECK._serialized_end=91
  _NOTIFYPROGRESS._serialized_start=93
  _NOTIFYPROGRESS._serialized_end=170
  _ERROR._serialized_start=172
  _ERROR._serialized_end=195
  _OK._serialized_start=197
  _OK._serialized_end=201
  _GETID._serialized_start=203
  _GETID._serialized_end=210
  _IDRESPONSE._serialized_start=212
  _IDRESPONSE._serialized_end=236
  _SETTRUST._serialized_start=238
  _SETTRUST._serialized_end=277
  _SETWORKABILITY._serialized_start=279
  _SETWORKABILITY._serialized_end=330
# @@protoc_insertion_point(module_scope)
