# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/command.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/command.proto\x12\x07\x63ommand\"\r\n\x0bStateUpdate\"\x17\n\x05\x45rror\x12\x0e\n\x06reason\x18\x01 \x01(\t\"=\n\x11\x43rawlPeersCommand\x12\x0f\n\x07restart\x18\x01 \x01(\x08\x12\x17\n\x0fmax_connections\x18\x02 \x01(\x03\".\n\x12\x43rawlPeersResponse\x12\x0b\n\x03num\x18\x01 \x01(\x03\x12\x0b\n\x03new\x18\x02 \x01(\x03\x42.Z,github.com/smartin015/peerprint/pubsub/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.command_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,github.com/smartin015/peerprint/pubsub/proto'
  _STATEUPDATE._serialized_start=32
  _STATEUPDATE._serialized_end=45
  _ERROR._serialized_start=47
  _ERROR._serialized_end=70
  _CRAWLPEERSCOMMAND._serialized_start=72
  _CRAWLPEERSCOMMAND._serialized_end=133
  _CRAWLPEERSRESPONSE._serialized_start=135
  _CRAWLPEERSRESPONSE._serialized_end=181
# @@protoc_insertion_point(module_scope)
