// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/raft.proto

package proto // import "github.com/smartin015/peerprint/pubsub/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetConsensusStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConsensusStatusRequest) Reset()         { *m = GetConsensusStatusRequest{} }
func (m *GetConsensusStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetConsensusStatusRequest) ProtoMessage()    {}
func (*GetConsensusStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_ac393660b4a555d5, []int{0}
}
func (m *GetConsensusStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConsensusStatusRequest.Unmarshal(m, b)
}
func (m *GetConsensusStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConsensusStatusRequest.Marshal(b, m, deterministic)
}
func (dst *GetConsensusStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConsensusStatusRequest.Merge(dst, src)
}
func (m *GetConsensusStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetConsensusStatusRequest.Size(m)
}
func (m *GetConsensusStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConsensusStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConsensusStatusRequest proto.InternalMessageInfo

type GetConsensusStatusResponse struct {
	Leader                string   `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	Followers             []string `protobuf:"bytes,3,rep,name=followers,proto3" json:"followers,omitempty"`
	LastElectionTimestamp uint64   `protobuf:"varint,4,opt,name=last_election_timestamp,json=lastElectionTimestamp,proto3" json:"last_election_timestamp,omitempty"`
	LogSize               uint64   `protobuf:"varint,5,opt,name=log_size,json=logSize,proto3" json:"log_size,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *GetConsensusStatusResponse) Reset()         { *m = GetConsensusStatusResponse{} }
func (m *GetConsensusStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetConsensusStatusResponse) ProtoMessage()    {}
func (*GetConsensusStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_ac393660b4a555d5, []int{1}
}
func (m *GetConsensusStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConsensusStatusResponse.Unmarshal(m, b)
}
func (m *GetConsensusStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConsensusStatusResponse.Marshal(b, m, deterministic)
}
func (dst *GetConsensusStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConsensusStatusResponse.Merge(dst, src)
}
func (m *GetConsensusStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetConsensusStatusResponse.Size(m)
}
func (m *GetConsensusStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConsensusStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConsensusStatusResponse proto.InternalMessageInfo

func (m *GetConsensusStatusResponse) GetLeader() string {
	if m != nil {
		return m.Leader
	}
	return ""
}

func (m *GetConsensusStatusResponse) GetFollowers() []string {
	if m != nil {
		return m.Followers
	}
	return nil
}

func (m *GetConsensusStatusResponse) GetLastElectionTimestamp() uint64 {
	if m != nil {
		return m.LastElectionTimestamp
	}
	return 0
}

func (m *GetConsensusStatusResponse) GetLogSize() uint64 {
	if m != nil {
		return m.LogSize
	}
	return 0
}

func init() {
	proto.RegisterType((*GetConsensusStatusRequest)(nil), "raft.GetConsensusStatusRequest")
	proto.RegisterType((*GetConsensusStatusResponse)(nil), "raft.GetConsensusStatusResponse")
}

func init() { proto.RegisterFile("proto/raft.proto", fileDescriptor_raft_ac393660b4a555d5) }

var fileDescriptor_raft_ac393660b4a555d5 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xcf, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x06, 0x60, 0xea, 0xd6, 0xd5, 0xe6, 0x24, 0x01, 0xb5, 0xab, 0x1e, 0xca, 0x9e, 0x7a, 0x90,
	0x46, 0x11, 0x7d, 0x00, 0x45, 0xbc, 0x77, 0x3d, 0x79, 0x29, 0xe9, 0x3a, 0x5b, 0x03, 0x69, 0x26,
	0x66, 0x26, 0x08, 0xfb, 0x3e, 0xbe, 0xa7, 0x34, 0x54, 0xbc, 0x78, 0x9a, 0x7f, 0xfe, 0x6f, 0x2e,
	0x23, 0x4e, 0x7c, 0x40, 0x46, 0x15, 0xf4, 0x8e, 0x9b, 0x14, 0x65, 0x3e, 0xe5, 0xf5, 0xa5, 0x58,
	0xbd, 0x00, 0x3f, 0xa1, 0x23, 0x70, 0x14, 0x69, 0xc3, 0x9a, 0x23, 0xb5, 0xf0, 0x19, 0x81, 0x78,
	0xfd, 0x9d, 0x89, 0x8b, 0xff, 0x94, 0xfc, 0xd4, 0xc8, 0x33, 0xb1, 0xb4, 0xa0, 0xdf, 0x21, 0x94,
	0x07, 0x55, 0x56, 0x17, 0xed, 0xbc, 0xc9, 0x2b, 0x51, 0xec, 0xd0, 0x5a, 0xfc, 0x82, 0x40, 0xe5,
	0xa2, 0x5a, 0xd4, 0x45, 0xfb, 0x57, 0xc8, 0x07, 0x71, 0x6e, 0x35, 0x71, 0x07, 0x16, 0xb6, 0x6c,
	0xd0, 0x75, 0x6c, 0x46, 0x20, 0xd6, 0xa3, 0x2f, 0xf3, 0x2a, 0xab, 0xf3, 0xf6, 0x74, 0xe2, 0xe7,
	0x59, 0x5f, 0x7f, 0x51, 0xae, 0xc4, 0xb1, 0xc5, 0xa1, 0x23, 0xb3, 0x87, 0xf2, 0x30, 0x1d, 0x1e,
	0x59, 0x1c, 0x36, 0x66, 0x0f, 0x8f, 0xcd, 0xdb, 0xf5, 0x60, 0xf8, 0x23, 0xf6, 0xcd, 0x16, 0x47,
	0x45, 0xa3, 0x0e, 0x6c, 0xdc, 0xcd, 0xed, 0xbd, 0xf2, 0x00, 0xc1, 0x07, 0xe3, 0x58, 0xf9, 0xd8,
	0x53, 0xec, 0x55, 0x7a, 0xbd, 0x5f, 0xa6, 0x71, 0xf7, 0x13, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xfa,
	0xef, 0x2c, 0x15, 0x01, 0x00, 0x00,
}
